package com.Tapia.ProyectoResidencia.Enum;

public enum Evento {
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    LOGIN_GOOGLE_EXITOSO,
    PASSWORD_RESET_SOLICITUD,
    PASSWORD_RESET_VERIFICADO,
    PASSWORD_RESET_COMPLETADO,
    REFRESH_TOKEN_EXITOSO,
    REFRESH_TOKEN_FALLIDO,
    USER_REGISTRADO,
    PRUEBAS
}
