package com.Tapia.ProyectoResidencia.Enum;

public enum Evento {
    //Login
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    LOGIN_GOOGLE_EXITOSO,

    //Recuperación
    PASSWORD_RESET_SOLICITUD,
    PASSWORD_RESET_SOLICITUD_SIN_VERIFICAR,
    PASSWORD_RESET_VERIFICADO,
    PASSWORD_RESET_COMPLETADO,
    PASSWORD_RESET_RECHAZADO,
    PASSWORD_RESET_ERROR,
    PASSWORD_RESET_FALLIDO,
    PASSWORD_RESET_EXITOSO,
    PASSWORD_RESET_TOKEN_INVALIDO,
    PASSWORD_RESET_TOKEN_EXPIRADO,

    //Refresh token
    REFRESH_TOKEN_EXITOSO,
    REFRESH_TOKEN_FALLIDO,
    TOKEN_ERROR_INTERNO_VALIDACION,

    //Registro
    USER_REGISTRADO,
    USER_REGISTRADO_GOOGLE,

    //Seguridad
    POSIBLE_ATAQUE_IP,

    //Actualización de datos de usuario
    UPDATE_INFO_USUARIO_EXITOSO,
    UPDATE_INFO_USUARIO_FALLIDO,

    //Cambio de contraseña
    PASSWORD_CHANGE_PRIMERA_VEZ,
    PASSWORD_CHANGE_EXITOSO,
    PASSWORD_CHANGE_FALLIDO,
    PASSWORD_CHANGE_ERROR,
    PASSWORD_CHANGE_RECHAZADO,
    PASSWORD_CHANGE_EXCESIVOS,

    //CRUD de vocalías
    VOCALIA_REGISTER_EXITOSO,
    VOCALIA_REGISTER_FALLIDO,
    VOCALIA_REGISTER_ERROR,
    VOCALIA_UPDATE_EXITOSO,
    VOCALIA_UPDATE_FALLIDO,
    VOCALIA_UPDATE_ERROR,
    VOCALIA_DELETE_EXITOSO,
    VOCALIA_DELETE_FALLIDO,
    VOCALIA_DELETE_ERROR,

    //Asignación de vocalías a usuarios
    ASIGNACION_VOCALIA_EXITOSO,
    ASIGNACION_VOCALIA_ERROR,
    //
    DESCONOCIDO
}
