package com.Tapia.ProyectoResidencia.Enum;

public enum Evento {
    //Login
    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    LOGIN_GOOGLE_EXITOSO,

    //Recuperación
    PASSWORD_RESET_SOLICITUD,
    PASSWORD_RESET_SOLICITUD_SIN_VERIFICAR,
    PASSWORD_RESET_VERIFICADO,
    PASSWORD_RESET_COMPLETADO,
    PASSWORD_RESET_RECHAZADO,
    PASSWORD_RESET_ERROR,
    PASSWORD_RESET_FALLIDO,
    PASSWORD_RESET_EXITOSO,
    PASSWORD_RESET_TOKEN_INVALIDO,
    PASSWORD_RESET_TOKEN_EXPIRADO,

    //Refresh token
    REFRESH_TOKEN_EXITOSO,
    REFRESH_TOKEN_FALLIDO,
    TOKEN_ERROR_INTERNO_VALIDACION,

    //Registro
    USER_REGISTRADO,
    USER_REGISTRADO_GOOGLE,

    //Seguridad
    POSIBLE_ATAQUE_IP,

    //Actualización de datos de usuario
    UPDATE_INFO_USUARIO_EXITOSO,
    UPDATE_INFO_USUARIO_FALLIDO,

    //Cambio de contraseña
    PASSWORD_CHANGE_PRIMERA_VEZ,
    PASSWORD_CHANGE_EXITOSO,
    PASSWORD_CHANGE_FALLIDO,
    PASSWORD_CHANGE_ERROR,
    PASSWORD_CHANGE_RECHAZADO,
    PASSWORD_CHANGE_EXCESIVOS,

    //CRUD de vocalías
    VOCALIA_REGISTER_EXITOSO,
    VOCALIA_REGISTER_FALLIDO,
    VOCALIA_REGISTER_ERROR,
    VOCALIA_UPDATE_EXITOSO,
    VOCALIA_UPDATE_FALLIDO,
    VOCALIA_UPDATE_ERROR,
    VOCALIA_DELETE_EXITOSO,
    VOCALIA_DELETE_FALLIDO,
    VOCALIA_DELETE_ERROR,

    //Asignación de vocalías a usuarios
    ASIGNACION_VOCALIA_EXITOSO,
    ASIGNACION_VOCALIA_ERROR,

    //Cambio de rol a usuarios
    UPDATE_ROL_USUARIO_EXITOSO,
    UPDATE_ROL_USUARIO_FALLIDO,
    UPDATE_ROL_USUARIO_ERROR,

    //Eliminar registro de la entidad Usuario
    DELETE_USUARIO_EXITOSO,
    DELETE_USUARIO_FALLIDO,
    DELETE_USUARIO_ERROR,

    //Respaldo de usuarios eliminados (auditoria)
    RESPALDO_USER_EXITOSO,
    RESPALDO_USER_FALLIDO,
    RESPALDO_USER_ERROR,

    //Actualizar correo de usuario (ADMIN)
    UPDATE_EMAIL_USUARIO_EXITOSO,
    UPDATE_EMAIL_USUARIO_FALLIDO,
    UPDATE_EMAIL_USUARIO_ERROR,

    //Actualizar contraseña de usuario (ADMIN)
    UPDATE_PASSWORD_ADMIN_EXITOSO,
    UPDATE_PASSWORD_ADMIN_FALLIDO,
    UPDATE_PASSWORD_ADMIN_ERROR,

    //Actualizar status de usuario (ADMIN)
    UPDATE_STATUS_ADMIN_EXITOSO,
    UPDATE_STATUS_ADMIN_ERROR,

    //Crear contrato (ADMIN & RRHH)
    CREATE_CONTRATO_EXITOSO,
    CREATE_CONTRATO_FALLIDO,
    CREATE_CONTRATO_ERROR,

    //Editar contrato (ADMIN & RRHH)
    UPDATE_CONTRATO_EXITOSO,
    UPDATE_CONTRATO_FALLIDO,
    UPDATE_CONTRATO_ERROR,

    //Eliminar contrato
    DELETE_CONTRATO_EXITOSO,
    DELETE_CONTRATO_ERROR,

    //Vincular contrato a un usuario (ADMIN & RRHH)
    ASIGNAR_CONTRATO_EXITOSO,
    ASIGNAR_CONTRATO_FALLIDO,
    ASIGNAR_CONTRATO_ERROR,

    //Editar vinculo de contrato a usuario (ADMIN & RRHH)
    UPDATE_VINCULO_CONTRATO_EXITOSO,
    UPDATE_VINCULO_CONTRATO_FALLIDO,
    UPDATE_VINCULO_CONTRATO_ERROR,

    //Crear un nuevo municipio (ADMIN)
    MUNICIPIO_REGISTER_EXITOSO,
    MUNICIPIO_REGISTER_ERROR,
    MUNICIPIO_REGISTER_FALLIDO,

    //Actualizar un nuevo municipio (ADMIN)
    MUNICIPIO_UPDATE_EXITOSO,
    MUNICIPIO_UPDATE_ERROR,
    MUNICIPIO_UPDATE_FALLIDO,

    //Eliminar un municipio (ADMIN)
    MUNICIPIO_DELETE_EXITOSO,
    MUNICIPIO_DELETE_ERROR,

    //Crear una nueva Zore (ADMIN)
    ZORE_REGISTER_EXITOSO,
    ZORE_REGISTER_ERROR,
    ZORE_REGISTER_FALLIDO,

    //Actualizar una Zore (ADMIN)
    ZORE_UPDATE_EXITOSO,
    ZORE_UPDATE_ERROR,
    ZORE_UPDATE_FALLIDO,

    //Crear una nueva Are (ADMIN)
    ARE_REGISTER_EXITOSO,
    ARE_REGISTER_ERROR,
    ARE_REGISTER_FALLIDO,

    //Actualizar una Are (ADMIN)
    ARE_UPDATE_EXITOSO,
    ARE_UPDATE_ERROR,
    ARE_UPDATE_FALLIDO,

    //Asignar Are a Zore (ADMIN)
    ASIGNACION_ZORE_ARE_REGISTRO_EXITOSO,
    ASIGNACION_ZORE_ARE_REGISTRO_FALLIDO,
    ASIGNACION_ZORE_ARE_REGISTRO_ERROR,

    //Actualizar Are a Zore (ADMIN)
    ASIGNACION_ZORE_ARE_UPDATE_EXITOSA,
    ASIGNACION_ZORE_ARE_UPDATE_FALLIDO,
    ASIGNACION_ZORE_ARE_UPDATE_ERROR,

    //
    LOCALIDAD_REGISTER_EXITOSO,
    LOCALIDAD_REGISTER_ERROR,
    LOCALIDAD_REGISTER_FALLIDO,

    //
    LOCALIDAD_UPDATE_EXITOSO,
    LOCALIDAD_UPDATE_ERROR,
    LOCALIDAD_UPDATE_FALLIDO,

    //
    LOCALIDAD_DELETE_EXITOSO,
    LOCALIDAD_DELETE_ERROR,

    //
    DESCONOCIDO
}
